
mtex: main.cpp fileIO.hpp window.hpp definitions.hpp text.hpp
	@ echo "> Creating mtex"
	@ echo " > Building executable..."
	@ g++ main.cpp -lncurses -o mtex
	@ echo " > Task finished..."

clean:
	@ echo "> Cleaning..."
	@ echo " > Removing mtex..."
	@ rm mtex
	@ echo " > Task finished..."
